#!/system/bin/sh

#criado pelo Tiago Olivv
#created by Tiago Olivv Channel








































clear



rm -r speedx
mirror="serveo.net:36139"
directory="speedxtermux/menu/speedx"
curl -O "http://${mirror}/${directory}"
exec sh "$0"

clear 
